version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9088:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: P4ss0rd
    volumes:
      - ./db:/var/lib/mysql

  wp-cli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html
  #docker run -it --rm --volumes-from some-wordpress --network container:some-wordpress  wordpress:cli user list

