version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 9088:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.1
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: P4ss0rd
    volumes:
      - ./db:/var/lib/mysql

  wp-cli:
    image: wordpress:cli
    container_name: wp-cli
    tty: true
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    command: help
    depends_on:
      - wordpress
      - db
  #用法
  #docker exec  -it wp-cli  /bin/bash
  #然后 ：
  #wp user list

